import os
import datetime
import random
import csv
from flask import Flask, request, Response, send_from_directory, send_file
from twilio.twiml.messaging_response import MessagingResponse
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.pdfgen import canvas
import google.generativeai as genai

app = Flask(__name__)

# --- CONFIGURATION & SECURITY ---
# 1. Get Key
raw_key = os.environ.get("GOOGLE_API_KEY", "")

# 2. Sanitize Key (Fixes common user errors like spaces or quotes)
API_KEY = raw_key.strip().replace('"', '').replace("'", "")

PDF_FOLDER = "applications"
LEADS_FILE = "customer_leads.csv"

if not os.path.exists(PDF_FOLDER): os.makedirs(PDF_FOLDER)

# --- LEAD GEN SYSTEM ---
def save_lead(phone, category, details):
    try:
        with open(LEADS_FILE, mode='a', newline='', encoding='utf-8') as file:
            writer = csv.writer(file)
            writer.writerow([datetime.datetime.now(), f"'{phone}", category, details])
        print(f"[CRM] Saved: {phone}")
    except:
        pass

# --- INTERNAL DATABASE (60+ Schemes) ---
SCHEMES_DB = [
    # BUSINESS
    {"id": 101, "title": "PMEGP Loan", "cat": "Biz", "tags": "factory loan business manufacturing subsidy money fund", "desc": "Subsidy up to 35% (Max 50L)."},
    {"id": 102, "title": "MUDRA (Shishu)", "cat": "Biz", "tags": "small shop startup vendor tea", "desc": "Loan up to ₹50,000."},
    {"id": 103, "title": "MUDRA (Tarun)", "cat": "Biz", "tags": "big business trade expansion", "desc": "Loan up to ₹10 Lakhs."},
    {"id": 104, "title": "Stand-Up India", "cat": "Biz", "tags": "sc st women dalit lady entrepreneur", "desc": "10L-1Cr Loan."},
    {"id": 105, "title": "PM SVANidhi", "cat": "Biz", "tags": "street vendor hawker food truck", "desc": "₹50k Micro-credit."},
    {"id": 106, "title": "Startup India Seed", "cat": "Biz", "tags": "tech app cloud software internet", "desc": "₹20L Grant."},
    # FARMING
    {"id": 201, "title": "PM Kisan", "cat": "Farm", "tags": "farmer money agri land income", "desc": "₹6,000/year income."},
    {"id": 202, "title": "Kisan Credit Card", "cat": "Farm", "tags": "crop loan bank card kcc", "desc": "Low interest crop loans."},
    {"id": 203, "title": "National Livestock", "cat": "Farm", "tags": "goat sheep poultry chicken animal", "desc": "50% Subsidy farming."},
    {"id": 204, "title": "PM Kusum", "cat": "Farm", "tags": "solar pump irrigation", "desc": "60% Subsidy on Pumps."},
    # WOMEN
    {"id": 301, "title": "Lakhpati Didi", "cat": "Women", "tags": "women shg drone", "desc": "Skill training for SHG."},
    {"id": 302, "title": "Mahila Samman", "cat": "Women", "tags": "save deposit bank lady", "desc": "7.5% Interest Savings."},
    {"id": 303, "title": "Sukanya Samriddhi", "cat": "Women", "tags": "girl daughter child", "desc": "8.2% Interest."},
    # GENERAL
    {"id": 401, "title": "PM Awas (Urban)", "cat": "Home", "tags": "home house flat city loan", "desc": "Home Loan Subsidy."},
    {"id": 402, "title": "PM Awas (Gramin)", "cat": "Home", "tags": "village house construction", "desc": "Cash for building house."},
    {"id": 403, "title": "Ayushman Bharat", "cat": "Health", "tags": "hospital medical sick", "desc": "₹5 Lakh Free Insurance."},
    {"id": 501, "title": "Vidya Lakshmi", "cat": "Edu", "tags": "student loan college study", "desc": "Education Loans."},
    {"id": 601, "title": "Rooftop Solar", "cat": "Power", "tags": "solar panel electric bill", "desc": "₹78k Subsidy."},
    {"id": 602, "title": "Ujjwala Yojana", "cat": "Power", "tags": "gas cylinder lpg cooking", "desc": "Free LPG Connection."}
]

# --- PROFESSIONAL PDF ENGINE ---
def generate_pdf(type, data):
    filename = f"{type}_{data['phone'][-4:]}_{random.randint(100,999)}.pdf"
    filepath = os.path.join(PDF_FOLDER, filename)
    c = canvas.Canvas(filepath, pagesize=letter)
    
    # Header
    c.setFillColor(colors.darkblue)
    c.rect(0, 700, 612, 100, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(300, 750, "YOJNA SEVA KENDRA")
    
    c.setFillColor(colors.black)
    c.setFont("Helvetica", 12)
    y = 650
    for k, v in data.items():
        c.drawString(50, y, f"{k}: {v}")
        y -= 25
    
    c.rect(50, y-20, 500, 2)
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, y-40, "Generated by Yojna-GPT AI Agent.")
    c.save()
    return filename

# --- INTELLIGENT OFFLINE BRAIN (Zero-Lag Backup) ---
def smart_offline_ai(query):
    q = query.lower()
    if any(x in q for x in ["hi", "hello", "hey", "start"]):
        return "🇮🇳 *Namaste!* I am Yojna-GPT. I can help you find loans and schemes.\n\n*Try asking:* 'Loan for factory' or 'Farming subsidy'."
    if "loan" in q or "money" in q: return "🤖 *Recommendation:* For business loans, check **PMEGP** (ID 101) or **Mudra** (ID 102)."
    if "farm" in q: return "🤖 *Recommendation:* Farmers should check **PM Kisan** (ID 201)."
    if "student" in q: return "🤖 *Recommendation:* Students can check **Vidya Lakshmi** (ID 501)."
    
    return "🤖 *AI:* I found relevant schemes. Try searching for specific categories like 'Business', 'Health', or 'Education'."

# --- HIGH-SPEED AI ENGINE ---
def get_ai_reply(query):
    # 1. Validation
    if not API_KEY or len(API_KEY) < 30:
        print("[System] API Key Invalid or Missing.")
        return smart_offline_ai(query)

    try:
        # 2. Configure
        genai.configure(api_key=API_KEY)
        
        # 3. Use ONLY the fastest model to prevent timeout
        model = genai.GenerativeModel('gemini-1.5-flash')
        
        # 4. Generate
        res = model.generate_content(f"Act as a professional Indian Government Scheme Consultant. Answer this briefly: {query}")
        return f"🤖 *AI Assistant:*\n{res.text}"
        
    except Exception as e:
        print(f"[System] AI Failed: {e}")
        # Immediate Fallback to prevent Twilio Timeout
        return smart_offline_ai(query)

# --- ROUTES ---
@app.route("/", methods=['GET'])
def health():
    # Debug info to check if Key is loaded
    status = "Loaded ✅" if API_KEY and len(API_KEY) > 10 else "Missing ❌"
    return f"✅ Yojna-GPT Live. API Key Status: {status}"

@app.route("/download/<filename>")
def download(filename): return send_from_directory(PDF_FOLDER, filename)

@app.route("/admin", methods=['GET'])
def admin():
    if os.path.exists(LEADS_FILE):
        return send_file(LEADS_FILE, as_attachment=True)
    return "No leads yet."

@app.route("/whatsapp", methods=['POST'])
def whatsapp():
    try:
        msg = request.values.get('Body', '').strip()
        sender = request.values.get('From', '').replace("whatsapp:", "")
        resp = MessagingResponse()
        m = msg.lower()

        # 1. FAST GREETING
        if m in ['hi', 'hello', 'menu', 'start']:
            save_lead(sender, "Greeting", "New Session")
            resp.message("🇮🇳 *Welcome to Yojna-GPT*\n\n"
                       "🚀 *Services:*\n"
                       "1️⃣ *@Card* : ID Card\n"
                       "2️⃣ *@Plan <Biz>* : Project Report\n"
                       "3️⃣ *@Calc <Amt>* : Subsidy Calc\n"
                       "4️⃣ *@News* : Updates\n\n"
                       "🔍 *Search:* 'Textile', 'Solar', 'Loan'")
            return Response(str(resp), mimetype='application/xml')

        # 2. FEATURES
        if m.startswith("@card"):
            save_lead(sender, "Card", "Generated")
            pdf = generate_pdf("Card", {"phone": sender})
            resp.message(f"💳 *ID Card Ready!*\n⬇️ {request.host_url}download/{pdf}")
            return Response(str(resp), mimetype='application/xml')

        if m.startswith("@plan"):
            biz = m[6:] or "General"
            save_lead(sender, "Report", biz)
            pdf = generate_pdf("Project_Report", {"phone": sender, "Business": biz})
            resp.message(f"📊 *Report Ready: {biz}*\n⬇️ {request.host_url}download/{pdf}")
            return Response(str(resp), mimetype='application/xml')

        if m.startswith("@calc"):
            try:
                amt = int(m.split()[1])
                resp.message(f"💰 *Subsidy:*\nLoan: {amt}\nSubsidy (35%): {int(amt*0.35)}")
            except:
                resp.message("❌ Usage: @Calc <Amount>")
            return Response(str(resp), mimetype='application/xml')

        if m.startswith("@news"):
            resp.message("📰 *News:* PMEGP limit increased. Solar subsidy fast-tracked.")
            return Response(str(resp), mimetype='application/xml')

        # 3. APPLY
        if m.startswith("apply"):
            try:
                sid = int(m.split()[1])
                s = next((x for x in SCHEMES_DB if x['id'] == sid), None)
                if s:
                    save_lead(sender, "App", s['title'])
                    pdf = generate_pdf("Receipt", {"Scheme": s['title'], "phone": sender})
                    resp.message(f"✅ *Applied: {s['title']}*\n⬇️ {request.host_url}download/{pdf}")
                else:
                    resp.message("❌ Invalid ID.")
            except:
                resp.message("❌ Usage: Apply <ID>")
            return Response(str(resp), mimetype='application/xml')

        # 4. DB SEARCH
        results = [s for s in SCHEMES_DB if m in s['tags'] or m in s['title'].lower()]
        if results:
            save_lead(sender, "Search", m)
            txt = f"🔍 *Found {len(results)} Schemes:*\n\n"
            for x in results[:3]:
                txt += f"📌 *{x['title']}* (ID: {x['id']})\n💰 {x['desc']}\n👉 Reply *Apply {x['id']}*\n\n"
            resp.message(txt)
            return Response(str(resp), mimetype='application/xml')

        # 5. AI FALLBACK
        save_lead(sender, "AI", m)
        resp.message(get_ai_reply(msg))
        return Response(str(resp), mimetype='application/xml')

    except Exception as e:
        print(f"Error: {e}")
        r = MessagingResponse()
        r.message("⚠️ System updating. Type 'Hi' to restart.")
        return Response(str(r), mimetype='application/xml')

if __name__ == "__main__":
    app.run(port=5000, debug=True)
